### ISSUE TITLE
about module ‘py_panther' error

### ISSUE THREAD

**Issue by w2385680516** [mit-acl/deep_panther#2]
python3 policy_compression_train.py

Traceback (most recent call last):
  File "policy_compression_train.py", line 27, in <module>
    from compression.policies.ExpertPolicy import ExpertPolicy
  File "/home/scout/deep_panther/src/deep_panther/panther_compression/compression/policies/ExpertPolicy.py", line 5, in <module>
    from compression.utils.other import ActionManager, ObservationManager, getPANTHERparamsAsCppStruct, ExpertDidntSucceed, computeTotalTime
  File "/home/scout/deep_panther/src/deep_panther/panther_compression/compression/utils/other.py", line 7, in <module>
    import py_panther
ModuleNotFoundError: No module named 'py_panther'

**Comment by jtorde** [comment]
Hi @w2385680516!

Did you run these commands? (see Readme)

```bash
printf '\nsource PATH_TO_YOUR_WS/devel/setup.bash' >> ~/.bashrc #Remember to change PATH_TO_YOUR_WS
printf '\nexport PYTHONPATH="${PYTHONPATH}:$(rospack find panther)/../panther_compression"' >> ~/.bashrc 
source ~/.bashrc
```

**Comment by w2385680516** [comment]
thank for your help！

**Comment by w2385680516** [comment]
I would like to ask how to collect data if I train the model, because the following error occurs when I run policy_compression_train.py：
![image](https://user-images.githubusercontent.com/49808908/224876740-72ee4329-daa4-4355-8355-5d2ac3f7a9a8.png)
